# Generated by Django 3.2.25 on 2024-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=500)),
                ('Lastname', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
            ],
        ),
    ]
